export const InventoryLocators = {
    appLogo: '.app_logo',
    productItems: '.inventory_item',
    addToCartButton: 'button',
    cartBadge: '.shopping_cart_badge',
    shoppingCartLink: '.shopping_cart_link',
    checkoutButton: '#checkout',
    firstNameInput: '#first-name',
    lastNameInput: '#last-name',
    postalCodeInput: '#postal-code',
    continueButton: '#continue',
    finishButton: '#finish',
    backToProductsButton: '#back-to-products',
    confirmationMessage: '.complete-header',
    burgerMenuButton: '#react-burger-menu-btn',
    title: '[data-test="title"]',
    logoutSidebarLink: '#logout_sidebar_link',
    sortProducts: '.product_sort_container',
    inventoryItemPrice: '[data-test="inventory-item-price"]',
    inventoryItemName: '[data-test="inventory-item-name"]',
};